/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RequestOptions {
  headers?: Record<string, string>
  timeout?: number
}
export declare function fetch(url: string, opts?: RequestOptions | undefined | null): Promise<Response>
export declare class Response {
  status: number
  body?: string
  url: string
  headers: Record<string, string>
  constructor(status: number, body?: string, url: string, headers: Record<string, string>)
}
